# Generated by Django 5.0.7 on 2024-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('username', models.TextField()),
                ('contact', models.PositiveBigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
    ]
